### ISSUE TITLE
wrong configuration inside each and every editor module of all the chapters

### ISSUE THREAD

**Issue by muzaheed57** [PacktPublishing/Unreal-Engine-4-Scripting-with-CPlusPlus-Cookbook#1]
wrong configuration inside each and every editor module of all the chapters.
any starter with c++ can figure out those wrong configuration.
so many careless  mistakes. surely the guy just copy pasted gameplay module to create editor module. he even did not care to run those chapters at least once to see if those works or not.

**Comment by sunithshetty** [comment]
Hi @muzaheed57 thank you for your feedback. We have raised your query with the Author. 

It will be great if you provide us a little more detail! What exactly did you find was wrongly configured?  (An example of an instance may be, Chapter number) ?

Please check the following: (Troubleshooting)
- If you have downloaded the code packages, the installation folder of your UE4 may differ.
- You may need to edit the .vcxproj files in .\Intermediate\ProjectFiles\ to have the correct PATH for your UE4 engine installation correctly to have this work properly.
- Alternatively you can construct new projects for each chapter on your PC and import the content files to your project.

Hope this helps!

Thanks
